# Build settings
markdown: kramdown

highlighter: rouge

plugins:
  - jekyll-redirect-from

#sass:
 # sass_dir: _sass

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - LICENSE


